services:
  backend:
    privileged: true
    build:
      context: .
      dockerfile: container/Dockerfile-backend
    environment:
      RUST_LOG: "info"
      SYMBOLICA_LICENSE: ""
    networks:
      - conn

  frontend:
    build:
      context: .
      dockerfile: container/Dockerfile-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - conn
    volumes:
      - ./container/Caddyfile:/dist/Caddyfile

networks:
  conn:
    driver: bridge
