[package]
name = "mrc"
version = "0.1.0"
edition = "2024"

[dependencies]
palc = { version = "0.0.1", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
simd-json = "0.15.1"
splines = "5.0.0"
