[package]
name = "cachegrind-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
raffine = { path = "../raffine" }
palc = { git = "https://github.com/oxalica/palc.git", features = ["derive"] }
anyhow = "1.0.98"
